osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/config/WebServiceConfig.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/services/NotificationService.java, osgp-core/src/main/resources/db/migration/V2015.013__Removed organisation_notification_url.sql, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Organisation.java
Fixes #152 
notification URL is now in the ws-adapter property file and can be changed at deployment
=> Removes the notification URL and moves it to a property file

osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringMonitoringEndpoint.java
Retrieving the same data twice caused a nullpointer exception, to I addes a nullcheck
=> Adds nullcheck Connects to #168

osgp-adapter-ws-admin/src/main/java/com/alliander/osgp/adapter/ws/admin/application/config/ApplicationContext.java, osgp-adapter-ws-admin/src/main/java/com/alliander/osgp/adapter/ws/admin/application/config/MessagingConfig.java, osgp-adapter-ws-admin/src/main/java/com/alliander/osgp/adapter/ws/admin/application/config/WebServiceConfig.java, osgp-adapter-ws-admin/src/main/java/com/alliander/osgp/adapter/ws/admin/application/services/DeviceManagementService.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/config/ApplicationContext.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/DeviceManagementService.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/endpoints/DeviceManagementEndpoint.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/DeviceFilter.java
=> Fixes security issue. Connects to SmartSocietyServices/Webapps#172

osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/DeviceManagementService.java
Low risk 36 - findAllOrganisations()
=> Fixes security issue. Connects to SmartSocietyServices/Webapps#173

.gitmodules, osgp-core/src/main/resources/db/migration/V2015.019__Added_restriction to_ean_ean_code.sql
Adds flyway script that changes the type of ean.code from varchar(255) to numeric(18).
Klaas' remark on the description length can be ignored for now.
=> Fixes Webapps/#211.

osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/mapping/ActualMeterReadsConverter.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/mapping/ActualMeterReadsRequestConverter.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/infra/jms/messageprocessor/ActualMeterReadsResponseMessageProcessor.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/ActualMeterReads.java
=> Adds license information to actual meter reads files.

osgp-adapter-ws-admin/src/main/java/com/alliander/osgp/adapter/ws/admin/application/services/DeviceManagementService.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/mapping/DeviceManagementMapper.java, osgp-adapter-ws-core/src/main/webapp/WEB-INF/wsdl/common/schemas/devicemanagement.xsd, osgp-core/src/main/java/com/alliander/osgp/core/application/services/EventNotificationMessageService.java, osgp-core/src/main/java/com/alliander/osgp/core/infra/jms/protocol/in/messageprocessors/EventNotificationMessageProcessor.java, osgp-core/src/main/resources/db/migration/V2015.020__Added_relay_status_table.sql, osgp-core/src/main/resources/db/migration/V2015.021__Added_relay_status_to_device.sql, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Device.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/RelayStatus.java
Connects to SmartSocietyServices/Webapps#248
Add device Overview
=> Feat devices overview. 

osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/mapping/DeviceManagementMapper.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/DeviceManagementService.java, osgp-adapter-ws-core/src/main/webapp/WEB-INF/wsdl/common/DeviceManagement.wsdl, osgp-adapter-ws-core/src/main/webapp/WEB-INF/wsdl/common/schemas/devicemanagement.xsd, osgp-adapter-ws-shared/src/main/java/com/alliander/osgp/adapter/ws/infra/specifications/JpaDeviceSpecifications.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Device.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/DeviceInterface.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/SmartMeteringDevice.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/specifications/DeviceSpecifications.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/DeviceFilter.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/DeviceInMaintenanceFilterType.java
Connects to SmartSocietyServices/Webapps#319
=> Feat device maintenance. Connects to SmartSocietyServices/Webapps#319

osgp-adapter-ws-core/src/main/webapp/WEB-INF/wsdl/common/schemas/devicemanagement.xsd
Connects to SmartSocietyServices/Webapps#313 SmartSocietyServices/Webapps#317
=> Bug relay4 not shown

osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/DeviceManagementService.java
Connects to SmartSocietyServices/Webapps#242
Now checks for OWNER and CONFIGURATION authorizations
=> Changes the setMaintenanceStatus authorization. Connects to SmartSocietyServices/Webapps/issues/242

osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/mapping/DeviceManagementMapper.java, osgp-adapter-ws-core/src/main/webapp/WEB-INF/wsdl/common/schemas/devicemanagement.xsd, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Device.java
Connects to SmartSocietyServices/Webapps#337
=> Feat flexovl view device management

.gitmodules, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/application/services/MonitoringService.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/ReadAlarmRegisterResponseMessageProcessor.java
Connects to SmartSocietyServices/Protocol-Adapter-DLMS/issues/41
- mapping from value object to value object
- casting to value object in protocol layer
=> solved mapping problems in read alarm register

osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringConfigurationEndpoint.java, osgp-adapter-ws-smartmetering/src/main/webapp/WEB-INF/wsdl/smartmetering/SmartMeteringConfiguration.wsdl, osgp-adapter-ws-smartmetering/src/main/webapp/WEB-INF/wsdl/smartmetering/schemas/sm-configuration.xsd
also renaming wsdl/xsd according to agreed naming conventions
=> connects to OSGP/Platform/issues/266 implement show result of set alarm notifications

.gitmodules, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/application/mapping/PeriodicMeterReadsConverter.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/mapping/PeriodicMeterReadsConverter.java, osgp-adapter-ws-smartmetering/src/main/webapp/WEB-INF/wsdl/smartmetering/schemas/sm-monitoring.xsd, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/ActualMeterReads.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/MeterReads.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/PeriodicMeterReads.java
=> Feat meter reads

osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/SmartMeter.java
=> Feat store security keys

.gitmodules, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/application/mapping/EventsConverter.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/mapping/EventConverter.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringManagementEndpoint.java, osgp-adapter-ws-smartmetering/src/main/webapp/WEB-INF/wsdl/smartmetering/schemas/sm-management.xsd, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/Event.java
https://smartsocietyservices.atlassian.net/browse/SLIM-256
=> Implementing eventCounter

osgp-adapter-domain-admin/src/main/java/com/alliander/osgp/adapter/domain/admin/application/services/DeviceManagementService.java, osgp-adapter-ws-admin/src/main/java/com/alliander/osgp/adapter/ws/admin/application/services/DeviceManagementService.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Ssld.java
- The fix assumes that this function is used for SSLD or PSLD devices (which is the case with the current code)
=> Fixes the upload keys function for a device. FLEX-1382

osgp-adapter-ws-admin/src/main/java/com/alliander/osgp/adapter/ws/admin/application/services/DeviceManagementService.java
- When a device exists, I checked whether the device type is SSLD or PSLD, but in some cases, the device type is not set.
=> Fixes uploading keys for SSLD and PSLD devices. FLEX-1382

osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/mapping/CosemDateTimeConverter.java, osgp-adapter-ws-smartmetering/src/test/java/com/alliander/osgp/adapter/ws/smartmetering/application/mapping/CosemDateTimeConverterTest.java
Adds a unit test for CosemDateTimeConverter.
=> SLIM-414 Fixes CosemDateTime converter for negative deviations.

osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/mapping/DeviceManagementMapper.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/DeviceManagementService.java, osgp-adapter-ws-core/src/main/webapp/WEB-INF/wsdl/common/schemas/devicemanagement.xsd, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Device.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Ean.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Ssld.java
* Refactors EAN code from String to long
* Adds EAN and isActivated code to updateDevice
=> FLEX-723 ~ Feat replace device

osgp-core/src/main/java/com/alliander/osgp/core/infra/jms/protocol/in/messageprocessors/PushNotificationSmsMessageProcessor.java
SLIM-434
Corrects misplaced registring a sms push notification as event
=> Slim 434 receive wakeup sms notification

.gitmodules, osgp-adapter-domain-publiclighting/src/main/java/com/alliander/osgp/adapter/domain/publiclighting/application/mapping/ScheduleConverter.java, osgp-adapter-domain-tariffswitching/src/main/java/com/alliander/osgp/adapter/domain/tariffswitching/application/mapping/ScheduleConverter.java, osgp-adapter-ws-publiclighting/src/main/webapp/WEB-INF/wsdl/publiclighting/schemas/pl-schedulemanagement.xsd, osgp-adapter-ws-tariffswitching/src/main/java/com/alliander/osgp/adapter/ws/tariffswitching/application/mapping/ws/TariffScheduleToScheduleConverter.java, osgp-adapter-ws-tariffswitching/src/main/webapp/WEB-INF/wsdl/tariffswitching/schemas/ts-schedulemanagement.xsd, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/Schedule.java
=> Feat flexovl elster flex 1542

.gitmodules, osgp-adapter-domain-publiclighting/src/main/java/com/alliander/osgp/adapter/domain/publiclighting/application/mapping/ScheduleConverter.java, osgp-adapter-domain-tariffswitching/src/main/java/com/alliander/osgp/adapter/domain/tariffswitching/application/mapping/ScheduleConverter.java, osgp-adapter-ws-core/src/main/webapp/WEB-INF/wsdl/common/schemas/configurationmanagement.xsd, osgp-adapter-ws-publiclighting/src/main/webapp/WEB-INF/wsdl/publiclighting/schemas/pl-schedulemanagement.xsd, osgp-adapter-ws-tariffswitching/src/main/java/com/alliander/osgp/adapter/ws/tariffswitching/application/mapping/ws/TariffScheduleToScheduleConverter.java, osgp-adapter-ws-tariffswitching/src/main/webapp/WEB-INF/wsdl/tariffswitching/schemas/ts-schedulemanagement.xsd, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/Configuration.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/Schedule.java
=> Feat flexovl elster flex 1586

osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/application/mapping/StandardUnitConverter.java, osgp-adapter-domain-smartmetering/src/test/java/com/alliander/osgp/adapter/domain/smartmetering/application/mapping/StandardUnitCalulatorTest.java
scaler = -3 => multiply by 10^-3 instead of divide by 10^-3
=> SLIM-247: fixed incorrect calculation of meter value with scaler <> 0

osgp-adapter-ws-core/src/main/webapp/WEB-INF/wsdl/common/schemas/firmwaremanagement.xsd
Made property Description on GetFirmwareVersionResponse optional
=> Made property Description on GetFirmwareVersionResponse optional

osgp-adapter-domain-core/src/main/java/com/alliander/osgp/adapter/domain/core/application/services/ConfigurationManagementService.java
Changed one getInternalIndex() too much in the previous US
=> FLEX-1624 ~ changes one use of the internal index back to the way is was

osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/application/services/InstallationService.java
Adds device authorization OWNER to a new device when it is added.
=> SLIM-510 Fix addDevice Method

osgp-adapter-ws-smartmetering/src/main/webapp/WEB-INF/wsdl/smartmetering/schemas/common.xsd
exception and resultString should be optional - SLIM-484
=> SLIM-484 Bug fix for bundle request happy flow

osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/application/services/AdhocService.java
=> Platform bug get conf obj - SLIM-478

osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/mapping/DeviceManagementMapper.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/DeviceManagementService.java, osgp-adapter-ws-core/src/main/webapp/WEB-INF/wsdl/common/schemas/devicemanagement.xsd, osgp-adapter-ws-shared/src/main/java/com/alliander/osgp/adapter/ws/infra/specifications/JpaDeviceSpecifications.java, osgp-core/src/main/resources/db/migration/V2016.028__Added_technical_installation_date_to_device.sql, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Device.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/specifications/DeviceSpecifications.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/DeviceFilter.java
=> FLEX-1849 Shows devices with an installation date

osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/mapping/DeviceManagementMapper.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/DeviceManagementService.java
=> FLEX-1849 Solves technical date issue for showing devices

.gitmodules, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/FirmwareManagementService.java, osgp-adapter-ws-shared-db/src/main/java/com/alliander/osgp/adapter/ws/shared/db/domain/repositories/writable/WritableDeviceModelRepository.java
=> Feat flexovl flex 1921

.gitmodules, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/mapping/DeviceFirmwareConverter.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/mapping/FirmwareConverter.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/mapping/FirmwareManagementMapper.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/FirmwareManagementService.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/endpoints/FirmwareManagementEndpoint.java, osgp-adapter-ws-core/src/main/webapp/WEB-INF/wsdl/common/FirmwareManagement.wsdl, osgp-adapter-ws-core/src/main/webapp/WEB-INF/wsdl/common/schemas/firmwaremanagement.xsd, osgp-adapter-ws-shared-db/src/main/java/com/alliander/osgp/adapter/ws/shared/db/domain/repositories/writable/WritableDeviceFirmwareRepository.java, osgp-adapter-ws-shared-db/src/main/java/com/alliander/osgp/adapter/ws/shared/db/domain/repositories/writable/WritableFirmwareRepository.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/DeviceFirmware.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Firmware.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/FirmwareModuleData.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/FirmwareVersion.java
=> Feat firmware version

.gitmodules, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/BundleResponseMessageProcessor.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringAdhocEndpoint.java, osgp-adapter-ws-smartmetering/src/main/webapp/WEB-INF/wsdl/smartmetering/schemas/common.xsd, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/ActionResponse.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/OsgpResultType.java
* Adds NOT OK result to ActionResponseDtos created when an exception has occurred.
* Adds Result to the response for a non bundled specific configuration object (no longer returning an exception message as ConfigurationData without further indication of error).
=> SLIM-612 introduce result status to operations to make errors clear

osgp-adapter-domain-admin/src/main/java/com/alliander/osgp/adapter/domain/admin/application/services/DeviceManagementService.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/mapping/DeviceConverterHelper.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/mapping/SsldConverter.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/DeviceManagementService.java, osgp-adapter-ws-core/src/main/webapp/WEB-INF/wsdl/common/schemas/devicemanagement.xsd, osgp-core/src/main/resources/db/migration/V2016.039__Adds_device_is_active.sql, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Device.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/services/DeviceDomainService.java
attribute to indicate if a device is (in)active. In the past the
attribute is_activated was misused to see if a device was (in)active.
=> Adds attribute is_active to the device entity. We will use this

osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/mapping/DeviceConverterHelper.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/mapping/SsldConverter.java
=> FLEX-2172 Solves bug new prop isActive for device for provisioning

osgp-adapter-ws-admin/src/main/java/com/alliander/osgp/adapter/ws/admin/application/services/DeviceManagementService.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/repositories/DeviceAuthorizationRepository.java
=> Feat flexovl flex 1988

osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Device.java
=> FLEX-2176 Sets device on active when registered

CONTRIBUTING.md, README.md
=> Update README.md en CONTRIBUTING.md

osgp-core/src/main/resources/db/migration/V2016.044__Migration_for_events.sql
=> FLEX-2075 Adds new migration script for events

osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/config/PersistenceConfig.java
This prevents database warnings 'No transaction in progress'.
Code is already tested.
=> Updated Single connection DataSource to HikariCP.

osgp-core/src/main/java/com/alliander/osgp/core/application/config/SchedulingConfig.java, osgp-core/src/main/java/com/alliander/osgp/core/application/tasks/EventRetrievalScheduledTask.java, osgp-core/src/main/resources/db/migration/V2017.003__Adds_index_on_event_table_for_device_and_date_time.sql, osgp-core/src/main/resources/osgp-core.properties, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/repositories/DeviceRepository.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/repositories/EventRepository.java
- adds scheduled task to retrieve event of devices of device models of a manufacturer
=> FLEX-2697 ~ Adds event retrieval for devices of a manufacturer.

osgp-core/src/main/java/com/alliander/osgp/core/application/config/PersistenceConfig.java
Fixes 'Detected resolved migration not applied to database' error message by setting Flyway out of order to true.
=> SLIM-942: Fixes 'Detected resolved migration not applied to database'

.gitmodules, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringAdhocEndpoint.java
=> Slim 895 create functional exceptions for failing device operations

osgp-adapter-domain-core/src/main/java/com/alliander/osgp/adapter/domain/core/application/services/AbstractService.java, osgp-adapter-domain-distributionautomation/src/main/java/org/osgpfoundation/osgp/adapter/domain/da/application/services/BaseService.java, osgp-adapter-domain-microgrids/src/main/java/com/alliander/osgp/adapter/domain/microgrids/application/services/BaseService.java, osgp-adapter-domain-publiclighting/src/main/java/com/alliander/osgp/adapter/domain/publiclighting/application/services/AbstractService.java, osgp-adapter-domain-tariffswitching/src/main/java/com/alliander/osgp/adapter/domain/tariffswitching/application/services/AbstractService.java, osgp-adapter-ws-admin/src/main/java/com/alliander/osgp/adapter/ws/admin/application/services/DeviceManagementService.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/DomainHelperService.java, osgp-adapter-ws-publiclighting/src/main/java/com/alliander/osgp/adapter/ws/publiclighting/application/services/DomainHelperService.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/services/DomainHelperService.java, osgp-adapter-ws-tariffswitching/src/main/java/com/alliander/osgp/adapter/ws/tariffswitching/application/services/DomainHelperService.java, osgp-core/src/main/java/com/alliander/osgp/core/application/services/DomainHelperService.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/services/DeviceDomainService.java
The DomainHelper classes all had a try-catch which was not useful any more, so the code has been removed.
=> FLEX-3266 ~ Removes unused exception throws statement.

osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/repositories/DeviceRepository.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/repositories/EanRepository.java
Hereby a fix to allow the custom queries in cucumber!
Is already tested for DA, should be tested for flexOvl, SM and microgrids too.
=> OC-376 Fix custom delete queries for Cucumber

osgp-adapter-ws-admin/src/main/resources/osgp-adapter-ws-admin.properties, osgp-adapter-ws-core/src/main/resources/osgp-adapter-ws-core.properties, osgp-adapter-ws-distributionautomation/src/main/resources/osgp-adapter-ws-distributionautomation.properties, osgp-adapter-ws-microgrids/src/main/resources/osgp-adapter-ws-microgrids.properties, osgp-adapter-ws-publiclighting/src/main/resources/osgp-adapter-ws-publiclighting.properties, osgp-adapter-ws-smartmetering/src/main/resources/osgp-adapter-ws-smartmetering.properties, osgp-adapter-ws-tariffswitching/src/main/resources/osgp-adapter-ws-tariffswitching.properties
This reverts commit 4164df6baf8e5bf9a6045567eefecc878c853d06.
=> Revert "FLEX-3263 ~ bug/jms template receive timeout (#624)"

osgp-core/src/main/resources/db/migration/V20170714145113221__Added_device_function_mapping_DistributionAutomation.sql
Added new functions for DA.
All in line with all other existing function mappings.
** This is also needed for adding DA Cucumber tests to the nightly builds.
=> Added default device function mappings to the migration scripts.

.gitmodules, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/repositories/ManufacturerRepository.java
=> Feature-SLIM-1017 add firmware manufacturers device types

.gitmodules, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/services/ActionMapperResponseService.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/services/ManagementService.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/services/MeterResponseDataService.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringBundleEndpoint.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringManagementEndpoint.java
=> SLIM-1225 Fix find events response when no events are found

.gitmodules, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/services/ActionMapperResponseService.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/services/ManagementService.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/services/MeterResponseDataService.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringBundleEndpoint.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringManagementEndpoint.java
=> SLIM-1443 Reverts code from SLIM-1225

osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/application/services/InstallationService.java, osgp-adapter-ws-admin/src/main/java/com/alliander/osgp/adapter/ws/admin/application/services/DeviceManagementService.java, osgp-adapter-ws-admin/src/main/java/com/alliander/osgp/adapter/ws/admin/endpoints/DeviceManagementEndpoint.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/mapping/DeviceInstallationMapper.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/AdHocManagementService.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/FirmwareManagementService.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringManagementEndpoint.java, osgp-core/src/main/java/com/alliander/osgp/core/infra/jms/domain/in/DomainResponseMessageListener.java, osgp-core/src/main/java/com/alliander/osgp/core/infra/jms/protocol/in/ProtocolRequestMessageListener.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Event.java
Removes among others TODOs that still need taking care of from the code.
These will have to get JIRA items in order to plan and track the effort.
Also removes a declaration of a not actually thrown exception, a
deprecated constructor that is not called and fixes a typo.
=> SLIM-1534 Removes TODOs and no longer used deprecated constructor

osgp-adapter-ws-admin/pom.xml, osgp-adapter-ws-admin/src/main/java/com/alliander/osgp/adapter/ws/admin/application/config/NotificationClientConfig.java, osgp-adapter-ws-admin/src/main/java/com/alliander/osgp/adapter/ws/admin/application/services/NotificationServiceWsAdmin.java, osgp-adapter-ws-admin/src/main/java/com/alliander/osgp/adapter/ws/admin/endpoints/DeviceManagementEndpoint.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/DeviceInstallationService.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/endpoints/DeviceManagementEndpoint.java, osgp-adapter-ws-shared/pom.xml, osgp-adapter-ws-shared/src/main/java/com/alliander/osgp/adapter/ws/clients/SendNotificationServiceClient.java, osgp-adapter-ws-shared/src/main/java/com/alliander/osgp/adapter/ws/endpointinterceptors/AnnotationMethodArgumentResolver.java
- notification when device authorizations are updated (ws-admin)
- notification when device is updated (ws-core)
- notification when in maintenance is updated (ws-core)
- notification when device life cycle is updated (ws-core)
=> FLEX-4022 ~ Adds notifications for device authorizations.

osgp-adapter-domain-microgrids/src/main/java/com/alliander/osgp/adapter/domain/microgrids/application/config/CommunicationMonitoringConfig.java, osgp-adapter-domain-microgrids/src/main/resources/osgp-adapter-domain-microgrids.properties
=> ZS-293 ~ Adds fixes for communication restore properties

osgp-adapter-ws-shared/src/main/java/com/alliander/osgp/adapter/ws/shared/services/AbstractNotificationServiceWs.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/config/SchedulingConfig.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/services/ResponseUrlDataCleanupJob.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/services/ResponseUrlDataCleanupService.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/domain/repositories/ResponseUrlDataRepository.java
The deleting is done by a clean up job.
Named this branch SLIM-1064 by mistake. It should be named SLIM-1604.
=> SLIM-1064: Keeps using custom urls by not deleting them after reading.

osgp-adapter-ws-shared/src/main/java/org/opensmartgridplatform/adapter/ws/clients/NotificationWebServiceTemplateFactory.java
The NotificationWebServiceTemplateFactory has both key store and trust
store dynamically configured. Because of this the trust store factory is
not defined as a bean here. Therefore afterPropertiesSet is not called
by Spring, but has to be explicitly invoked as already was the case with
the key store.
=> OC-380 Fix trust store initialization in template factory
