OSGP/Platform

osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/ws/WebServiceResponseMessageSender.java
Fixes #155.
The issue was that some exceptions don't have a cause, which results in a nullpointer when calling __responseMessage.getOsgpException().getCause().getMessage()__
=> Bug fix 155. Connects to #155

osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/OsgpCoreResponseMessageProcessor.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/ActualMeterReadsResponseMessageProcessor.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/AddMeterResponseMessageProcessor.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/FindEventsResponseMessageProcessor.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/GetAdministrativeStateResponseMessageProcessor.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/PeriodicMeterReadsresponseMessageProcessor.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/ReadAlarmRegisterResponseMessageProcessor.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/SetActivityCalendarResponseMessageProcessor.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/SetAdministrativeStatusResponseMessageProcessor.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/SetAlarmNotificationsResponseMessageProcessor.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/SetConfigurationObjectResponseMessageProcessor.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/SpecialDaysResponseMessageProcessor.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/SynchronizeTimeResponseMessageProcessor.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringAdhocEndpoint.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringConfigurationEndpoint.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringEndpoint.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringInstallationEndpoint.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringManagementEndpoint.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringMonitoringEndpoint.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/infra/jms/messageprocessor/DomainResponseMessageProcessor.java, osgp-core/src/main/java/com/alliander/osgp/core/application/services/DeviceResponseMessageService.java, osgp-core/src/main/java/com/alliander/osgp/core/infra/jms/domain/DomainResponseMessageSender.java
When the retry mechanism was fixed, it became necessary to send the
initial request data back with a response for failure, to allow
resending it.
This caused issues with response message processors that were not up for
this task, which have been taken care of as well.
Fixes OSGP/Platform#315
=> Fixes retry loop caused by not incrementing retry counter.

osgp-adapter-ws-smartmetering/src/main/webapp/WEB-INF/wsdl/smartmetering/schemas/sm-adhoc.xsd, osgp-adapter-ws-smartmetering/src/main/webapp/WEB-INF/wsdl/smartmetering/schemas/sm-configuration.xsd, osgp-adapter-ws-smartmetering/src/main/webapp/WEB-INF/wsdl/smartmetering/schemas/sm-installation.xsd
If the result is OK, no description is required. Hence, the tag is made
optional.
=> fixes bug SLIM-432

osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Device.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/DeviceAuthorization.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/DomainInfo.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Ean.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Event.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Organisation.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/ProtocolInfo.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/RelayStatus.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/ScheduledTask.java
- domain entities should only use business key values, not collections or object identifiers to calculate a hash
- see: https://developer.jboss.org/wiki/EqualsAndHashCode?_sscc=t
=> Reimplements hashCode() and equals() functions for domain entities. FLEX-1377

osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/repositories/DeviceFunctionMappingRepository.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/services/SecurityService.java
For an organization that has no authorizations on a device, a NotAuthorizedException is thrown instead of a SQL grammar related exception.
=> SLIM-481 SLIM-460 Bug on authorization check for organistation without device

osgp-adapter-domain-smartmetering/src/test/java/com/alliander/osgp/adapter/domain/smartmetering/application/services/AdministrativeStatusTypeMappingTest.java, osgp-adapter-domain-smartmetering/src/test/java/com/alliander/osgp/adapter/domain/smartmetering/application/services/PeriodicMeterReadContainerMappingTest.java, osgp-adapter-domain-smartmetering/src/test/java/com/alliander/osgp/adapter/domain/smartmetering/application/services/PeriodicMeterReadsContainerGasMappingTest.java, osgp-adapter-domain-smartmetering/src/test/java/com/alliander/osgp/adapter/domain/smartmetering/application/services/PeriodicMeterReadsQueryMappingTest.java, osgp-adapter-domain-smartmetering/src/test/java/com/alliander/osgp/adapter/domain/smartmetering/application/services/PushSetupAlarmMappingTest.java, osgp-adapter-domain-smartmetering/src/test/java/com/alliander/osgp/adapter/domain/smartmetering/application/services/PushSetupSmsMappingTest.java, osgp-adapter-domain-smartmetering/src/test/java/com/alliander/osgp/adapter/domain/smartmetering/application/services/SetConfigurationObjectRequestMappingTest.java, osgp-adapter-ws-smartmetering/src/test/java/com/alliander/osgp/adapter/ws/smartmetering/application/mapping/AdministrativeStatusTypeMappingTest.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/AdministrativeStatusType.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/AlarmType.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/AmrProfileStatusCodeFlag.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/ClockStatusBit.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/ConfigurationFlagType.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/GprsOperationModeType.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/MessageType.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/PeriodType.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/TransportServiceType.java
Changes some tests to call name() method directly instead of useless
value() method
=> SLIM-532_Remove_unused_methods_from_enums

osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/OsgpCoreResponseMessageProcessor.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/core/messageprocessors/BundleResponseMessageProcessor.java
If a retryable exception occurs handling a bundle of actions, and the
maximum number of retries has been reached, the exception is propagated
through the platform.
These changes preserve any separate action responses before the
exception occurred, and place the exception as response for all actions
that did not yet have a response.
=> SLIM-646 Handle bundle exception through separate action responses.

osgp-adapter-ws-core/src/main/webapp/WEB-INF/wsdl/common/FirmwareManagement.wsdl
2 warnings were shown when validating the FirmwareManagement.wsdl file.
- WS-I: (BP2118) A wsdl:binding does not have the same list of wsdl:operations as the wsdl:portType to which it refers.
- WS-I: (BP2120) A binding has operations that are not unique.
The operations FindAllManufacturers, AddManufacturer, ChangeManufacturer and RemoveManufacturer were all duplicated in the wsdl:binding section.
These duplicate operation definitions have been removed.
The 4 operation were tested using SoapUI and using a client application.
Further, the WSDL file has been formatted.
=> FLEX-2313 ~ Resolves WSDL warnings.

osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/validation/TlsConfigurationValidator.java
- If the tlsPortNumber is omitted, the validation was incorrect.
=> FLEX-2294 ~ Fixes validation when only tlsEnabled is used.

osgp-core/src/main/resources/db/migration/V2016.055__Adds_indexes_to_device_authorization.sql
In order to speed up processing of the authorization checks when
processing a web service request, adds an index to foreign key
references to device and organization.
=> SLIM-812 Adds indexes on table device_authorizations.

.gitmodules, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/application/services/MonitoringService.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/mapping/MonitoringMapper.java, osgp-core/src/main/java/com/alliander/osgp/core/application/tasks/ScheduledTaskScheduler.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/CaptureObjectDefinition.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/ObisCodeValues.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/ProfileGenericDataRequest.java
Brings selective access for profile generic to the
command executor.
* Adds value object for CaptureObjectDefinition.
* Adds toString to ObisCodeValues.
* Cleans up equals and hashCode for ObisCodeValues.
* Adds selectedValues to ProfileGenericDataRequest.
* Makes ProfileGenericDataRequest properly immutable.
* Adds toString to ProfileGenericDataRequest.
* Cleans up ProfileGenericDataRequest equals and hashCode.
* Simplifies mapping to ProfileGenericDataRequestDto.
* Configures MonitoringMapper to be able to map
selectedValues.
=> SLIM-900 Implement selective access for Load Profile

osgp-adapter-ws-microgrids/src/main/java/com/alliander/osgp/adapter/ws/microgrids/application/config/WebServiceConfig.java, osgp-adapter-ws-microgrids/src/main/java/com/alliander/osgp/adapter/ws/microgrids/application/services/NotificationServiceWs.java, osgp-adapter-ws-microgrids/src/main/resources/osgp-adapter-ws-microgrids.properties, osgp-adapter-ws-shared/src/main/java/com/alliander/osgp/adapter/ws/shared/services/AbstractNotificationServiceWs.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/config/WebServiceConfig.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/services/NotificationServiceWs.java, osgp-adapter-ws-smartmetering/src/main/resources/osgp-adapter-ws-smartmetering.properties
Uses OSGP client certificate for notifications.
* Adds web.service.notification.organisation to
smartmetering ws configuration properties
* Adds web.service.notification.organisation to
microgrids ws configuration properties
* Configures the NotificationServiceWS for
smartmetering and microgrids to use the configured
organisation (OSGP) for the web service template
for sending notifications.
=> OC-305 Use OSGP client certificate to send notifications

osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/mapping/PeriodicMeterReadsRequestConverter.java
Adds the canConvert implementation according to the 1.4.6
version of Orika to the PeriodicMeterReadsRequestConverter.
With the 1.5.1 version in the CustomConverter the mapping of
the WS PeriodicReadsRequest does not use this converter and
fails.
=> SLIM-873 Fixes Orika converter after upgrade to 1.5.1

osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/config/WebServiceConfig.java
Makes sure the details for a technical exception are
included with a SOAP fault as well as those for
functional exceptions.
=> SLIM-1008 Fix failing Cucumber tests

.gitmodules, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/application/services/MBusGatewayService.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/infra/jms/ws/messageprocessors/CoupleMbusDeviceRequestMessageProcessor.java
Added for coupling channel and primaryaddress, since they are needed for coupling unbound devices.
=> Slim 976 couple unbound connected

osgp-core/src/main/java/com/alliander/osgp/core/infra/jms/protocol/in/messageprocessors/GetFirmwareFileMessageProcessor.java
The FirmwareFileDto needs identification and file bytes of a firmware
file. The identification used to be by filename, but this was no longer
considered to be a unique identifier.
=> SLIM-1222 Fix end-to-end FirmwareUpdate

osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringBundleEndpoint.java
This helps the cucumber scenario 'Bundle 3 operations that all need to bypass retrying' to
succeed.
=> Handles the not ok situation for a bundle. 

osgp-adapter-domain-publiclighting/src/main/java/com/alliander/osgp/adapter/domain/publiclighting/application/services/AdHocManagementService.java, osgp-adapter-domain-publiclighting/src/main/java/com/alliander/osgp/adapter/domain/publiclighting/application/tasks/BaseTask.java
- refactors code of handleLightMeasurementDeviceTransition() in order to
reduce the number of lined of the function and to include the setting of
the last communication time of a light measurement device when an event
is received.
- makes sure that the device contacting is executed after OSGP has
started before the age of events for light measurement devices are
evaluated in order to speed up contacting devices.
=> FLEX-3830 ~ Sets last communication time for LMDs.

osgp-adapter-domain-core/src/main/java/com/alliander/osgp/adapter/domain/core/application/services/AbstractService.java, osgp-adapter-domain-distributionautomation/src/main/java/org/osgpfoundation/osgp/adapter/domain/da/application/services/BaseService.java, osgp-adapter-domain-microgrids/src/main/java/com/alliander/osgp/adapter/domain/microgrids/application/services/BaseService.java, osgp-adapter-domain-publiclighting/src/main/java/com/alliander/osgp/adapter/domain/publiclighting/application/services/AbstractService.java, osgp-adapter-domain-publiclighting/src/main/java/com/alliander/osgp/adapter/domain/publiclighting/application/services/DeviceMonitoringService.java, osgp-adapter-domain-smartmetering/src/main/java/com/alliander/osgp/adapter/domain/smartmetering/application/services/DomainHelperService.java, osgp-adapter-domain-tariffswitching/src/main/java/com/alliander/osgp/adapter/domain/tariffswitching/application/services/AbstractService.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/DeviceManagementService.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/DomainHelperService.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/application/services/FirmwareManagementService.java, osgp-adapter-ws-core/src/main/java/com/alliander/osgp/adapter/ws/core/endpoints/DeviceManagementEndpoint.java, osgp-adapter-ws-publiclighting/src/main/java/com/alliander/osgp/adapter/ws/publiclighting/application/services/DomainHelperService.java, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/services/DomainHelperService.java, osgp-adapter-ws-tariffswitching/src/main/java/com/alliander/osgp/adapter/ws/tariffswitching/application/services/DomainHelperService.java, osgp-core/src/main/java/com/alliander/osgp/core/application/services/DomainHelperService.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/entities/Ssld.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/services/DeviceDomainService.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/services/SmartMeterDomainService.java
Resolves the following potential bug:
* Puts equals implementation in Ssld extending Device.
Resolves the following potential vulnerabilities:
* Use a catch block instead of instanceof in DeviceMonitoringService.
* Throws FunctionalException as only thrown checked exception in
DeviceManagementService.
* Removes exception or throws a dedicated exception with several methods
of FirmwareManagementService.
* Throws only one checked exception in DeviceDomainService, changes
callers to include component type, so the same repeated structure of
creating a FunctionalException is only in one location.
* Updates the SmartMeterDomainService in a similar way as the
DeviceDomainService.
=> SLIM-1534 Resolves SonarQube reported bugs and vulnerabilities

osgp-adapter-ws-microgrids/src/main/java/com/alliander/osgp/adapter/ws/microgrids/infra/jms/messageprocessors/AbstractDomainResponseMessageProcessor.java
The message processor called from the context of a message listener's
onMessage method causes retries by the re-delivery mechanism configured
on the queue that is listened on when certain exceptions are thrown from
the implementation (JMSException, RuntimeException or Error).
Exceptions from sending notifications are only logged, and not re-thrown
to avoid re-delivery of the response data that may already have been
retrieved by the application in the mean time.
Exceptions extracting the meta-data that lead to unrecoverable error
being logged are now also IllegalArgumentException and
NullPointerException, since these could occur creating the enum values
or in some situations while getting JMS properties.
=> ZS-312 Updates message processor to prevent retries from queue

osgp-adapter-domain-core/src/main/java/com/alliander/osgp/adapter/domain/core/infra/jms/ws/messageprocessors/CommonSetDeviceLifecycleStatusRequestMessageProcessor.java, osgp-adapter-ws-smartmetering/src/main/resources/osgp-adapter-ws-smartmetering.properties
Changes configuration for notification service URL
The default configuration for the notifications is changed so it matches
the URL where the Cucumber tests will provide a notification service
end-point.
=> SLIM-869 Create an integration test https notification service

osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/application/config/ApplicationContext.java
Within a Spring Configuration class bean methods returning an instance
of a class that implements the BeanFactoryPostProcessor interface must
be static to prevent possible issues with some types of annotations.
=> Makes BeanFactoryPostProcessor bean static in Spring Configuration

.gitmodules, osgp-adapter-ws-smartmetering/src/main/java/com/alliander/osgp/adapter/ws/smartmetering/endpoints/SmartMeteringAdhocEndpoint.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/MbusChannelShortEquipmentIdentifier.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/MbusShortEquipmentIdentifier.java, osgp-domain-core/src/main/java/com/alliander/osgp/domain/core/valueobjects/smartmetering/ScanMbusChannelsResponseData.java
On Scan M-Bus Channels all attributes identifying the M-Bus device per
channel should be returned. These are represented conform the M-Bus
Short Equipment Identifier (Short ID) attributes (Identification number,
Manufacturer identification, Version identification, Device type
identification).
* Adds MbusShortEquipmentIdentifier as value object for the M-Bus Short
ID.
* Adds MbusChannelShortEquipmentIdentifier as value object for the M-Bus
Short ID on a particular channel.
* Updates ScanMbusChannelsResponse to have a list of M-Bus Short IDs per
channel instead of four M-Bus identification numbers.
* Updates the SmartMeteringAdhocEndpoint to return the list of Short IDs
as result for scan M-Bus channels instead of the four identification
numbers.
=> SLIM-1775 Adds value objects for Short IDs on scan M-Bus channels

osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/BundleService.java, osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/ConfigurationService.java, osgp-adapter-domain-smartmetering/src/main/java/org/opensmartgridplatform/adapter/domain/smartmetering/application/services/FirmwareService.java, osgp-core/src/main/resources/db/migration/V20181003143231399__Adds_device_firmware_module.sql, osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/entities/Device.java, osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/entities/DeviceFirmwareModule.java, osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/repositories/DeviceFirmwareModuleRepository.java, osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/repositories/DeviceRepository.java, osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/repositories/FirmwareModuleRepository.java, osgp-domain-core/src/main/java/org/opensmartgridplatform/domain/core/valueobjects/FirmwareModuleData.java
Adds table device_firmware_module to osgp_core to have a place to store
information about versions of firmware modules that are known to be
active on a device.
Updates code where firmware module versions as retrieved from a device
are handled, to store these versions in the database.
=> SLIM-1542 Manage firmware version data based on responses from a device
